# Generated by Django 6.0.2 on 2026-02-12 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('case_title', models.CharField(max_length=255)),
                ('case_type', models.CharField(choices=[('Civil', 'Civil'), ('Criminal', 'Criminal'), ('Corporate', 'Corporate'), ('Family', 'Family'), ('Property', 'Property')], default='Civil', max_length=50)),
                ('court_name', models.CharField(max_length=255)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Closed', 'Closed'), ('Decree', 'Decree')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
