# Generated by Django 6.0.2 on 2026-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='next_hearing',
            field=models.DateField(blank=True, null=True),
        ),
    ]
