# Generated by Django 6.0.2 on 2026-02-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_advocatefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocatefile',
            name='file_type',
            field=models.CharField(max_length=255),
        ),
    ]
