# Generated by Django 6.0.2 on 2026-03-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_advocatefile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
