# Generated by Django 6.0.2 on 2026-03-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_reminder_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='related_case',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='related_client',
        ),
        migrations.RemoveField(
            model_name='task',
            name='case',
        ),
        migrations.RemoveField(
            model_name='task',
            name='client',
        ),
        migrations.AddField(
            model_name='reminder',
            name='case_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='case_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
